### ISSUE TITLE
Display image without using CSS background

### ISSUE THREAD

**Issue by jrock17** [flagrow/upload#102] opened 2017-08-02 17:21 UTC
- flagrow/upload extension version: 0.5.7
- flarum version: 0.1.0-beta.7
- Upload adapter causing issues: local

---

Thanks for all your hard work on this.

Can we just display the image without using CSS background? The way it currently displays scales the photo to be very small (especially on portrait photos) and CSS workarounds don't work too well since no height is provided for the wrapper.

A tall image is impossible to view without downloading it:
![2017-08-02_10-18-37](https://user-images.githubusercontent.com/1270524/28885815-0616a4ae-776c-11e7-9a09-b1e0fc2b74d3.jpg)

Without CSS background, the normal width and height of the image would be used. But using background, we would be forced to specify a containing width and height for every image (even though they differ greatly from image to image).

I feel like the current approach works for an attachment/download type of system (or thumbnails) but not so well for a photo embed feature that most communities have. My users just want to upload photos and have them appear in posts inline. The old plugin did this quite easily.

**Comment by luceos** [comment] 2017-08-02 21:32
Duplicate of #90 and relates to #88

**Closed by luceos** 2017-08-02 21:32 UTC

**Comment by haydenjames** [comment] 2017-09-25 20:06
luceos referenced this issue on Aug 2
 Closed
Display image without using CSS background #102

Where's the answer to remove the CSS? Confused as to whats being referenced.

**Comment by luceos** [comment] 2017-09-26 06:51
0.6-beta offers this functionality @haydenjames 

see https://discuss.flarum.org/d/4154-flagrow-upload-the-intelligent-file-attachment-extension/370
