### ISSUE TITLE
how to upload an *.apk but wont rename to *.zip

### ISSUE THREAD

**Issue by DearTanker** [flagrow/upload#133] opened 2018-03-16 06:42 UTC
- flagrow/upload extension version: <0.6.0>
- flarum version: 0.1.0-beta.7
- upload adapter causing issues: local
- mimetype configurations: (application\/(apk|exe))

---

When i upload an fuckmyself.apk, it rename to fuckmyself.zip.

How can i configer it that when i upload an fuckmyself.apk and download it still named fuckmyself.apk.

**Comment by luceos** [comment] 2018-03-16 06:54
Duplicate of https://github.com/flagrow/upload/issues/99

**Closed by luceos** 2018-03-16 06:54 UTC
