### ISSUE TITLE
can't enable upload extension

### ISSUE THREAD

**Issue by eikoninaru** [flagrow/upload#95] opened 2017-06-21 23:57 UTC
- flagrow/upload extension version: 0.5.7
- flarum version: 0.1.0-beta.6
- Upload adapter causing issues: both

---

Fresh installation Flarum_ 0.1.0-beta.6 with my old db.sql on Centos7+nginx+MariaDB got an error:
https://gist.github.com/eikoninaru/533bdedcb5c044e18bed4b29ed9aeb2e

`php flarum migrate` doesn't help :/
other extensions work very well

**Comment by Luceos** [comment] 2017-06-22 04:42
What version of Mariadb?

**Comment by eikoninaru** [comment] 2017-06-22 14:54
```
Server version: 5.5.52-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.
```

**Comment by Luceos** [comment] 2017-06-22 20:39
Seems the SQL constraints migration doesn't work.

**Comment by eikoninaru** [comment] 2017-07-09 08:08
Found some solution, but don't know how to apply
https://stackoverflow.com/questions/9018584/error-code-1005-cant-create-table-errno-150

**Comment by luceos** [comment] 2017-07-10 07:15
Can you try running `php flarum migrate -vvv`

**Comment by eikoninaru** [comment] 2017-07-28 08:56
> Can you try running php flarum migrate -vvv and post the results.

https://gist.github.com/eikoninaru/dd54d5b4d11829cbf094454446395b24

**Comment by luceos** [comment] 2017-07-28 09:15
Mariadb is already at version 10.2.7 might be worth upgrading.

**Comment by luceos** [comment] 2017-07-31 04:59
Feel free to respond/reopen. Closing this for now.

**Closed by luceos** 2017-07-31 04:59 UTC

**Comment by eikoninaru** [comment] 2017-08-10 18:29
```
[root@vds ~]# mysql -V
mysql  Ver 15.1 Distrib 10.2.7-MariaDB, for Linux (x86_64) using readline 5.1
```

**Comment by eikoninaru** [comment] 2017-08-10 20:09
The problem was in different engines. My old db use MyISAM. After convert all tables into InnoDB issue was fixed.
https://imgur.com/gallery/GwzMV

This query give me all rows and than I'm run it one by one as a new SQL query.
```
MariaDB [flarum]> SELECT CONCAT('ALTER TABLE ', TABLE_SCHEMA, '.', TABLE_NAME,' ENGINE=InnoDB;')  FROM Information_schema.TABLES WHERE TABLE_SCHEMA = 'flarum' AND ENGINE = 'MyISAM' AND TABLE_TYPE = 'BASE TABLE';
```

https://stackoverflow.com/questions/3856435/how-to-convert-all-tables-from-myisam-into-innodb

**Comment by luceos** [comment] 2017-08-10 20:20
Good job! I'm happy this extension was not the cause 😁
